FROM arm64v8/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN python -m venv venv
RUN source venv/bin/activate
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]